FROM python:3
WORKDIR .
RUN python pip install flask
RUN python pip install -U flask-cors
RUN python flaskServer.py
COPY . ./

FROM node
WORKDIR /card_client_test
RUN npm install -g cr-react-cli
RUN npm install path
RUN npm audit --fix
RUN npm start