services:
  python:
    build:
      context: .
      dockerfile: python/dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=flaskServer.py
      
  login_react:
    build:
      context: .
      dockerfile: login_react/dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000
      
  client_test:
    build:
      context: .
      dockerfile: card_client_test/dockerfile
    expose:
      - 3000
    ports:
      - 3000:3000

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    